const scheduleData = {
  Andre: {
    1: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: C-tur",
      "Tors: Ledig",
      "Fre: Ledig",
      "Lör: H1",
      "Sön: H1",
    ],
    2: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: D1",
      "Tors: D2",
      "Fre: D1",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    3: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: Ledig",
      "Tors: Ledig",
      "Fre: DE",
      "Lör: H2",
      "Sön: H2",
    ],
    4: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: DE",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    5: [
      "Mån: D1",
      "Tis: D2",
      "Ons: C-tur",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    6: [
      "Mån: D2",
      "Tis: D1",
      "Ons: D2",
      "Tors: D1",
      "Fre: D2",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
  },
  Göran: {
    1: [
      "Mån: D2",
      "Tis: D1",
      "Ons: D2",
      "Tors: D1",
      "Fre: D2",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    2: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: C-tur",
      "Tors: Ledig",
      "Fre: Ledig",
      "Lör: H1",
      "Sön: H1",
    ],
    3: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: D1",
      "Tors: D2",
      "Fre: D1",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    4: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: Ledig",
      "Tors: Ledig",
      "Fre: DE",
      "Lör: H2",
      "Sön: H2",
    ],
    5: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: DE",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    6: [
      "Mån: D1",
      "Tis: D2",
      "Ons: C-tur",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
  },
  Zacharias: {
    1: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: D1",
      "Tors: D2",
      "Fre: D1",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    2: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: Ledig",
      "Tors: Ledig",
      "Fre: DE",
      "Lör: H2",
      "Sön: H2",
    ],
    3: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: DE",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    4: [
      "Mån: D1",
      "Tis: D2",
      "Ons: C-tur",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    5: [
      "Mån: D2",
      "Tis: D1",
      "Ons: D2",
      "Tors: D1",
      "Fre: D2",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    6: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: C-tur",
      "Tors: Ledig",
      "Fre: Ledig",
      "Lör: H1",
      "Sön: H1",
    ],
  },
  Peter: {
    1: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: Ledig",
      "Tors: Ledig",
      "Fre: DE",
      "Lör: H2",
      "Sön: H2",
    ],
    2: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: DE",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    3: [
      "Mån: D1",
      "Tis: D2",
      "Ons: C-tur",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    4: [
      "Mån: D2",
      "Tis: D1",
      "Ons: D2",
      "Tors: D1",
      "Fre: D2",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    5: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: C-tur",
      "Tors: Ledig",
      "Fre: Ledig",
      "Lör: H1",
      "Sön: H1",
    ],
    6: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: D1",
      "Tors: D2",
      "Fre: D1",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
  },
  Bshar: {
    1: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: DE",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    2: [
      "Mån: D1",
      "Tis: D2",
      "Ons: C-tur",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    3: [
      "Mån: D2",
      "Tis: D1",
      "Ons: D2",
      "Tors: D1",
      "Fre: D2",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    4: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: C-tur",
      "Tors: Ledig",
      "Fre: Ledig",
      "Lör: H1",
      "Sön: H1",
    ],
    5: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: D1",
      "Tors: D2",
      "Fre: D1",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    6: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: Ledig",
      "Tors: Ledig",
      "Fre: DE",
      "Lör: H2",
      "Sön: H2",
    ],
  },
  Sebastian: {
    1: [
      "Mån: D1",
      "Tis: D2",
      "Ons: C-tur",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    2: [
      "Mån: D2",
      "Tis: D1",
      "Ons: D2",
      "Tors: D1",
      "Fre: D2",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    3: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: C-tur",
      "Tors: Ledig",
      "Fre: Ledig",
      "Lör: H1",
      "Sön: H1",
    ],
    4: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: D1",
      "Tors: D2",
      "Fre: D1",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
    5: [
      "Mån: C-tur",
      "Tis: C-tur",
      "Ons: Ledig",
      "Tors: Ledig",
      "Fre: DE",
      "Lör: H2",
      "Sön: H2",
    ],
    6: [
      "Mån: Ledig",
      "Tis: Ledig",
      "Ons: DE",
      "Tors: C-tur",
      "Fre: C-tur",
      "Lör: Ledig",
      "Sön: Ledig",
    ],
  },
};

export default scheduleData;
